export const svgWidth = 320;
export const svgHeight = 240;
export const offsetX = 30; // x좌표 어긋난 정도
export const offsetY = 10; // y좌표 어긋난 정도
export const initDataSet = [120, 70, 175, 80, 220, 40, 180, 70, 90];
export const dataMax = 300; // 데이터 최대값
export const barWidth = 20; // 막대 너비
export const barMargin = 5; // 막대 옆 간격
export const labels = ['A','B','C','D','E','F','G','H','I','J','K','L'];