import {
  easeBack,
  easeBounce,
  easeCircle,
  easeCubic,
  easeElastic,
  easeExp,
  easeLinear,
  easePoly,
  easeQuad,
  easeSin,
} from 'd3';
import { Ease } from '@/types/measureOfDispersion';
import {
  easeBackIn,
  easeBackInOut,
  easeBackOut,
  easeBounceIn,
  easeBounceInOut,
  easeBounceOut,
  easeCircleIn,
  easeCircleInOut,
  easeCircleOut,
  easeCubicIn,
  easeCubicInOut,
  easeCubicOut,
  easeElasticIn,
  easeElasticInOut,
  easeElasticOut,
  easeExpIn,
  easeExpInOut,
  easeExpOut,
  easePolyIn,
  easePolyInOut,
  easePolyOut,
  easeQuadIn,
  easeQuadInOut,
  easeQuadOut,
  easeSinIn,
  easeSinInOut,
  easeSinOut,
} from 'd3-ease';

export const eases: Ease[] = [
  { label: 'easeLinear', value: easeLinear },
  { label: 'easePoly', value: easePoly },
  { label: 'easePolyIn', value: easePolyIn },
  { label: 'easePolyOut', value: easePolyOut },
  { label: 'easePolyInOut', value: easePolyInOut },
  { label: 'easeQuad', value: easeQuad },
  { label: 'easeQuadIn', value: easeQuadIn },
  { label: 'easeQuadOut', value: easeQuadOut },
  { label: 'easeQuadInOut', value: easeQuadInOut },
  { label: 'easeCubic', value: easeCubic },
  { label: 'easeCubicIn', value: easeCubicIn },
  { label: 'easeCubicOut', value: easeCubicOut },
  { label: 'easeCubicInOut', value: easeCubicInOut },
  { label: 'easeSin', value: easeSin },
  { label: 'easeSinIn', value: easeSinIn },
  { label: 'easeSinOut', value: easeSinOut },
  { label: 'easeSinInOut', value: easeSinInOut },
  { label: 'easeExp', value: easeExp },
  { label: 'easeExpIn', value: easeExpIn },
  { label: 'easeExpOut', value: easeExpOut },
  { label: 'easeExpInOut', value: easeExpInOut },
  { label: 'easeCircle', value: easeCircle },
  { label: 'easeCircleIn', value: easeCircleIn },
  { label: 'easeCircleOut', value: easeCircleOut },
  { label: 'easeCircleInOut', value: easeCircleInOut },
  { label: 'easeElastic', value: easeElastic },
  { label: 'easeElasticIn', value: easeElasticIn },
  { label: 'easeElasticOut', value: easeElasticOut },
  { label: 'easeElasticInOut', value: easeElasticInOut },
  { label: 'easeBack', value: easeBack },
  { label: 'easeBackIn', value: easeBackIn },
  { label: 'easeBackOut', value: easeBackOut },
  { label: 'easeBackInOut', value: easeBackInOut },
  { label: 'easeBounce', value: easeBounce },
  { label: 'easeBounceIn', value: easeBounceIn },
  { label: 'easeBounceOut', value: easeBounceOut },
  { label: 'easeBounceInOut', value: easeBounceInOut },
];
